### ISSUE TITLE
Is the repo alive?

### ISSUE THREAD

**Issue by maxkoryukov** [arjunkomath/node-freshdesk-api#1]
Hello! Thanks for this package;)

I would like to use it for my tiny project, but I need **Companies** stuff. I have already added all required functions to my local copy of your package, but I could send you a pull request (and we will have a better version of the package)

Are there a chance to update the package on the NPM?

**Comment by maxkoryukov** [comment]
ping @arjunkomath

**Comment by maxkoryukov** [comment]
ping @arjunkomath again

**Comment by maxkoryukov** [comment]
ping @arjunkomath

**Comment by arjunkomath** [comment]
Sorry for the delay. Your PR has been merged.
