### ISSUE TITLE
promisifyAll example is broken

### ISSUE THREAD

**Issue by gajus** [arjunkomath/node-freshdesk-api#104]
```js
const freshdesk = promisifyAll(
  new Freshdesk('https://aboutsnack.freshdesk.com', argv.freshdeskApiKey),
);

await freshdesk.createTicket({
  description: 'test description',
  email: 'test@test.com',
  name: 'test ticket',
  priority: 1,
  status: 2,
  subject: 'test sub',
});

```

gives error:

```
/Users/gajus/Documents/dev/snack/snack-api/node_modules/freshdesk-api/lib/utils.js:112
			return cb(null, data, extra)
			       ^

TypeError: cb is not a function
    at Request._callback (/Users/gajus/Documents/dev/snack/snack-api/node_modules/freshdesk-api/lib/utils.js:112:11)
    at Request.self.callback (/Users/gajus/Documents/dev/snack/snack-api/node_modules/request/request.js:185:22)

```

**Comment by gajus** [comment]
Even the regular promisify is not going to work:

```js
const freshdesk = new Freshdesk('https://aboutsnack.freshdesk.com', argv.freshdeskApiKey);

const createTicket = promisify(freshdesk.createTicket.bind(freshdesk));

await createTicket({
  description: 'test description',
  email: 'test@test.com',
  name: 'test ticket',
  priority: 1,
  status: 2,
  subject: 'test sub',
});

```

```
(node:92969) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_auth' of undefined
    at createTicket (/Users/gajus/Documents/dev/snack/snack-api/node_modules/freshdesk-api/lib/client.js:113:28)
    at internal/util.js:297:30
    at new Promise (<anonymous>)

```

You need to bind the context to make it work `promisify(freshdesk.createTicket.bind(freshdesk))`.

**Comment by arjunkomath** [comment]
@gajus Thanks for reporting the issue, I'll investigate this.

**Comment by gajus** [comment]
@arjunkomath Can you also have a look if I can get https://snack.freshdesk.com sub-domain? It seems like it is used by some inactive account.

**Comment by arjunkomath** [comment]
> @arjunkomath Can you also have a look if I can get https://snack.freshdesk.com sub-domain? It seems like it is used by some inactive account. (Sorry for a sneaky support request. Didn't want a straightforward way to raise a ticket for this.)

Not sure how I can check this, I don't work for Freshdesk.

**Comment by arjunkomath** [comment]
@gajus I tested using bluebird and it  seems to be working as expected, only thing is that you should add async at the end of the function name. This is the code I tried:

```js
const freshdesk = bluebird.promisifyAll(new Freshdesk('https://test.freshdesk.com', 'blahblah'));

const tickets = await freshdesk.listAllTicketsAsync({});
console.log(tickets);
```

**Comment by arjunkomath** [comment]
> Even the regular promisify is not going to work:
> 
> ```js
> const freshdesk = new Freshdesk('https://aboutsnack.freshdesk.com', argv.freshdeskApiKey);
> 
> const createTicket = promisify(freshdesk.createTicket.bind(freshdesk));
> 
> await createTicket({
>   description: 'test description',
>   email: 'test@test.com',
>   name: 'test ticket',
>   priority: 1,
>   status: 2,
>   subject: 'test sub',
> });
> ```
> 
> ```
> (node:92969) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_auth' of undefined
>     at createTicket (/Users/gajus/Documents/dev/snack/snack-api/node_modules/freshdesk-api/lib/client.js:113:28)
>     at internal/util.js:297:30
>     at new Promise (<anonymous>)
> ```
> 
> You need to bind the context to make it work `promisify(freshdesk.createTicket.bind(freshdesk))`.

Can you try `createTicketAsync` method?

**Comment by gajus** [comment]
> Can you try createTicketAsync method?

![download](https://user-images.githubusercontent.com/973543/91856964-db4a0980-ec2c-11ea-96ac-d0e7f1f26a6e.jpg)

That works.
