### ISSUE TITLE
getAll* calls are misleading

### ISSUE THREAD

**Issue by tehnorm** [arjunkomath/node-freshdesk-api#123]
* [X] freshdesk-api V2
* [ ] freshdesk-api V1 (obsolete)

## Current behavior

When calling an endpoint that will paginate it does not return ALL records - it returns only the records in the initial API response.

## Expected behavior

Return ALL records via pagination.

## More details

It seems this is already sort of considered: https://github.com/arjunkomath/node-freshdesk-api/blob/d4f5aebc61164acef6d5bbc3ae055a803c03e28a/lib/utils.js#L80

**Comment by arjunkomath** [comment]
@tehnorm  Have you tried paginating using `page` parameter?
