### ISSUE TITLE
How to create contact using this module

### ISSUE THREAD

**Issue by ranvirgorai** [arjunkomath/node-freshdesk-api#14]
i want to use all other api feather like create contact group etc... it is possible to use those feather using this module if yes then how ??

**Comment by arjunkomath** [comment]
@ranvirgorai Groups are not yet implemented. Its pretty easy to add though. In case you clone and add the feature youself, feel free to add a PR. 👍

**Comment by maxkoryukov** [comment]
@ranvirgorai, you could subscribe to this issue -  #25 to watch progress
