### ISSUE TITLE
Expose pagination from headers

### ISSUE THREAD

**Issue by pongstr** [arjunkomath/node-freshdesk-api#15]
Hey @arjunkomath, I was wondering  if it's possible to also return/expose pagination details from
the headers and return an `object` instead of `array` like so:

```javascript
{
  data: [
    { ... },
    { ... },
    { ... }
  ],
  per_page: 10,
  pages: 2,
  next_url: 'https://test.freshdesk.com/api/v2/tickets/?per_page=10&pages=2'
}
```

**Comment by arjunkomath** [comment]
@maxkoryukov What do you suggest, should we implement this? It will break existing requests, but can be implemented.

**Comment by maxkoryukov** [comment]
@arjunkomath , @pongstr I am sure, this already implemented.

Try this:

```javascript

var Freshdesk = require('freshdesk-api')
var f = new Freshdesk('https://yourdomain.freshdesk.com', 'asdf')

var params = {page: 1}
f.listAllTickets(params, (err, d) => { console.log(err, d); })

```

this should work for you;)

**Comment by maxkoryukov** [comment]
@arjunkomath , could you add me to the Collaborator list for this repo?

https://help.github.com/articles/permission-levels-for-a-user-account-repository/

**Comment by pongstr** [comment]
@maxkoryukov 

would be nice to traverse pages based on results returned from the request. Since headers are not passed to the `callback`, we'll have to calculate the amount of pages left which the API already does. See [Freshdesk API Pagination](https://developer.freshdesk.com/api/#pagination)

@arjunkomath yea, it's definitely going to break stuff, perhaps its a `0.2.x` feature?
