### ISSUE TITLE
npm WARN deprecated request@2.88.2: request has been deprecated

### ISSUE THREAD

**Issue by ricardotormo** [arjunkomath/node-freshdesk-api#173]
* [x] freshdesk-api V2
* [ ] freshdesk-api V1 (obsolete)

## Current behavior
The package is working just fine, but I think it would be good to update some npm dependencies.

Could be possible to replace request package, which is deprecated, to another one like got, for example?

## Expected behavior
Having a new http request package that is not deprecated

## More details

_provide the output of `npm version` in the root of your package_

```
{ 'freshdesk-api': '2.12.0',
  npm: '6.14.11',
}
```

**Comment by arjunkomath** [comment]
@ricardotormo that's a good suggestion, I can look into it.

**Comment by arjunkomath** [comment]
Fixed in #174

**Comment by ricardotormo** [comment]
It was pretty quick!
Do you plan to merge this branch to the master?
Thank you.

**Comment by arjunkomath** [comment]
It's already merged.
