### ISSUE TITLE
Create reply with attachment failing: "(TypeError): form.getHeaders is not a function"

### ISSUE THREAD

**Issue by BakulTessell** [arjunkomath/node-freshdesk-api#191]
Hi,

I am trying to update a ticket with an attachment but it's failing with the below error:

```
Unhandled Rejection (TypeError): form.getHeaders is not a function

utils.js:159 Uncaught (in promise) TypeError: form.getHeaders is not a function
    at makeRequest (utils.js:159)
    at Freshdesk.createReply (client.js:226)
    at uploadScreenshot (QuickTicket.jsx:211)
```

The payload is:
```
    {
      body: ReactDOMServer.renderToString(rDesc),
      from_email: user.email,
      attachments: [
        sStream
      ],
    };
```

I followed the instructions on https://www.npmjs.com/package/freshdesk-api to attach a file.
Am I missing something?

**Comment by BakulTessell** [comment]
Found the issue.
When using this package in a browser, the FormData object doesn't have a getHeaders() method.
If the line #159 in `utils.js` is changed to:
```
options.headers["Content-Type"] = "multipart/form-datai";
```
Then this issue is resolved.

@arjunkomath @maxkoryukov ,
Is it possible t push this fix in the next update?

**Comment by arjunkomath** [comment]
Thanks for looking into the issue, I'll investigate this today, hopefully release a fix soon.
