### ISSUE TITLE
typo in the description of the repo

### ISSUE THREAD

**Issue by maxkoryukov** [arjunkomath/node-freshdesk-api#2]
@arjunkomath plz, fix the typo in the description of the repo

**Comment by arjunkomath** [comment]
Fixed by @maxkoryukov in #5

**Comment by maxkoryukov** [comment]
Still there, the description of the github repository: `Node wrapper for Freshdesh v2 API`

Freshde**SH** )))

**Comment by arjunkomath** [comment]
@maxkoryukov Fixed 👍
