### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by dsouzamanish** [arjunkomath/node-freshdesk-api#20]
When using listAllConversations method of module. following error is returned.
```
TypeError: cb is not a function
    at Request._callback (/Users/manish/Remitr/projects/remitr-common/freshdesk/node_modules/node-freshdesk-api/lib/utils.js:63:11)
    at Request.self.callback (/Users/manish/Remitr/projects/remitr-common/freshdesk/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
```.


On further debugging i found that there is a small error in lib/client.js

```js
listAllConversations(id, cb) {
		makeRequest('GET', this._auth, `${this.baseUrl}/api/v2/tickets/${id}/conversations`, null, cb)
	},
```

callback cb is passed as 5th parameter instead of 6th.

```
listAllConversations(id, cb) {
		makeRequest('GET', this._auth, `${this.baseUrl}/api/v2/tickets/${id}/conversations`, null, null, cb)
	},
```

Please update the repo accordingly

**Comment by maxkoryukov** [comment]
Thank you, will be fixed soon

**Comment by maxkoryukov** [comment]
@dsouzamanish that could be your pullrequest ;) but it is too late ­— it is already fixed

**Comment by maxkoryukov** [comment]
my gosh... 8 commits and 3 version for one patch... Sorry guys, I need to sleep for awhile...

**Comment by maxkoryukov** [comment]
@dsouzamanish , fixed, new version is on NPM already;)

I have closed this issue, bcz I am sure, the bug (typo) is fixed

You could reopen any time;)
