### ISSUE TITLE
[Question] how to get all tickets using listAllTickets

### ISSUE THREAD

**Issue by saostad** [arjunkomath/node-freshdesk-api#201]
I tried to use docs to figure out how to get all tickets from API, but it's just giving me the first 30 tickets; I can see in the extra object there are more pages but don't know how to get those.
Could you please show me an example of that use case?

Thanks

**Comment by arjunkomath** [comment]
Refer: https://developer.freshdesk.com/api/#list_all_tickets
![CleanShot 2022-01-21 at 11 02 09](https://user-images.githubusercontent.com/2555067/150441396-1309fe97-4174-4e9d-8967-d320ce1045ab.png)

have you tried passing `page: 2` as filter?

**Comment by saostad** [comment]
I expected to get all the ticket items by running the function once, so should I run the operation as many pages? Like in a loop?

**Comment by arjunkomath** [comment]
You cannot get all tickets in one call, you'll have to call fresh desk API multiple times, it is clearly mentioned in their documentation https://developer.freshdesk.com/api/#pagination
