### ISSUE TITLE
Replace axios with undici

### ISSUE THREAD

**Issue by kibertoad** [arjunkomath/node-freshdesk-api#242]
## Current behavior

axios is used as an http client

## Expected behavior

undici is used as an http client

## More details

undici is significantly faster than clients, based on node `http` module, such as axios: https://github.com/nodejs/undici#benchmarks

If this is approved, I can work on PR.

**Comment by arjunkomath** [comment]
Sounds good, thanks.

**Comment by kibertoad** [comment]
@arjunkomath It would be a semver major, though, because if someone was mocking these calls with nock before, they would have to use undici mocks instead (as it doesn't use node "net" module).
btw, do you intentionally maintain callback API? if you are ok to move to promise-based api only, I can do so within same PR

**Comment by arjunkomath** [comment]
Since it's a major semver we can do both, break the existing implementation and go for promises.

**Comment by kibertoad** [comment]
@arjunkomath Is compatibility with browser important for this library? Undici only works in Node.js, so if browser support is important, this change should not be made.

**Comment by arjunkomath** [comment]
@kibertoad I don't think this library should be used in a browser as it uses a private API key.
