### ISSUE TITLE
utilize JSDoc

### ISSUE THREAD

**Issue by maxkoryukov** [arjunkomath/node-freshdesk-api#28]
This will make `README.md` shorter and will help us to keep docs updated.

- [x] Generate documentation
- [ ] autopublish docs
- [ ] add namespaces for documentation (there is a mess)
- [ ] add `CompanyResponse`, `TimeEntryResponse` to the html, currently they are excluded (it is a bug)

**Comment by maxkoryukov** [comment]
**Generate documentation** -- done. Need to autopublish it

**Comment by arjunkomath** [comment]
✅ Docs are automatically deployed to http://arjunkomath.github.io/node-freshdesk-api/
