### ISSUE TITLE
Implement Solutions

### ISSUE THREAD

**Issue by maxkoryukov** [arjunkomath/node-freshdesk-api#35]
Not implemented: http://developers.freshdesk.com/api/#solutions

**Comment by joelcox** [comment]
We will be integrating with Freshdesk and will be needing this functionality. You can expect a PR for at least part of this API.

**Comment by joelcox** [comment]
My first stab can be found [here](https://github.com/pixelpillow/node-freshdesk-api/tree/solutions-api). Feedback is appreciated.

**Comment by arjunkomath** [comment]
@joelcox could you create a PR?

**Comment by joelcox** [comment]
@arjunkomath Sorry for the late reply. I created a MR [here](https://github.com/arjunkomath/node-freshdesk-api/pull/72). Let me know what you think before I resolve conflicts.
