### ISSUE TITLE
Bring back all tickets

### ISSUE THREAD

**Issue by ghost** [arjunkomath/node-freshdesk-api#52]
Hi,

There isnt any documentation in regards to this node package as to how you bring back all tickets through the "extra" parameter e.g. freshdesk.listAllTickets((err,data,extra){ console.log(extra) } <

this brings back an object pageIsLast = true,

How can play around with extras because its only bringing back 20 tickets when there are over 100...

**Comment by zbrba** [comment]
Gday - did you work this one out? Thanks.

**Comment by thedatascienceguy** [comment]
Hi Zbrba,

I did manage to figure it out by using the old API.

This one is V2 but V1 was able or rather had the ability to put url addresses in the functions.

e.g.

freshdesk.get('tickets/per_page=100', data,err) {
// do stuff
}

Hope that helps.

You can find the API here incase youre wondering: https://github.com/kumarharsh/node-freshdesk

**Comment by maxkoryukov** [comment]
Hello!

As you can see we deprecated the V1 API created by @kumarharsh, and moved it into this repository: https://github.com/arjunkomath/node-freshdesk-api/tree/API-v1

If you already know, how to use `extra` argument with a new Freshdesk API - let's implement it, and make the new API better!

I will try to update the documentation about `extra` in next few days (maybe, weeks... :cry: )

**Comment by arjunkomath** [comment]
@maxkoryukov Shouldn't `per_page` work with current API, Check additional example 3, https://developers.freshdesk.com/api/#list_all_tickets
