### ISSUE TITLE
Update ticket attachments

### ISSUE THREAD

**Issue by lyes96** [arjunkomath/node-freshdesk-api#53]
Good morning,

I have an issue with updating attachments of a ticket in the freshdesk-api V2.

## Current behavior

When I try to update the attachment, I get this error 
[ { field: 'attachments',
    message: 'It should contain elements of type valid file format only',
    code: 'datatype_mismatch' } ]

## Expected behavior

The attachments field is supposed to be an array of objects so I provided that. My code is in the attached file below.

## Code
[update.pdf](https://github.com/arjunkomath/node-freshdesk-api/files/2180593/update.pdf)

## Details

{freshdesk-api: 2.5.0'
 npm: '5.6.0',
  ares: '1.14.0',
  cldr: '33.0',
  http_parser: '2.8.0',
  icu: '61.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.29.0',
  node: '10.1.0',
  openssl: '1.1.0h',
  tz: '2018c',
  unicode: '10.0',
  uv: '1.20.2',
  v8: '6.6.346.27-node.6',
  zlib: '1.2.11' }

Thank you.

**Comment by Mayurran** [comment]
Did you find a solution? I'm having the same problem...
