### ISSUE TITLE
Validation error on getTicket

### ISSUE THREAD

**Issue by stefanve** [arjunkomath/node-freshdesk-api#61]
If do:  
`freshdesk.updateTicket(8, {description: "foo"}, cb);`
all is fine, ticket gets updated and so on

but when I do:
`freshdesk.getTicket(8, cb);`

I get:
```
 name: 'FreshdeskError',
 message: 'Validation failed',
 data.errors[0] {
  "field": "ticket",
  "message": "Unexpected/invalid field in request",
  "code": "invalid_field"
}
```

I get similar if I try `listAllTickets` 

I can make the calls through curl and HTTP.call without problems.

Strange.

**Comment by arjunkomath** [comment]
@stefanve I'm unable to reproduce the issue.

**Comment by stefanve** [comment]
That was a

> @stefanve I'm unable to reproduce the issue.

That was a quick close. I can reproduce it. I guess you don't care.

**Comment by kamlekar** [comment]
I am facing the same issue.

**Comment by kamlekar** [comment]
ok, the issue is with when we keep `https://example.freshdesk.com/`. (_the ending slash_)

We just have to remove the ending slash and it all works fine.

**Comment by arjunkomath** [comment]
No wonder I couldn't reproduce the issue. Thanks @kamlekar 

The docs specify:
```js
var freshdesk = new Freshdesk('https://yourdomain.freshdesk.com', 'yourApiKey')
```

maybe I should add a note that there shouldn't be trailing `/` at the end?

**Comment by stefanve** [comment]
No, as you can read in my initial message:
`freshdesk.updateTicket(8, {description: "foo"}, cb);` works fine
`freshdesk.getTicket(8, cb);` does not.
Both use, or used, the same instance of 'freshdesk'.

**Comment by arjunkomath** [comment]
@stefanve That's strange. Pretty difficult to debug the issue without reproducing it. 😢

**Comment by stefanve** [comment]
I guess. I could have provided you with code last year but now I have abandoned the project. There were other calls that also returned error "Unexpected/invalid field in request"
If I recall correctly, it was those 'get' which only needed the id.

Thinking about it, maybe the trailing slash could be the culplrit, depending on how the freshdesk object assembles and format the request.

**Comment by kamlekar** [comment]
Yeah seems trailing slash is the culprit as @arjunkomath here just providing the wrapper and not transforming the code anywhere.

When I was dealing with this issue I gone through the code and saw nothing which changes the code. So, I concluded the error should be at my point which made me check the way I am keeping the domain. (_pretty tough to analyze this.. wasted 5 hours on this_). Yeah, it is better to keep a note of warning in docs to mention the same.

BTW, thanks for this @arjunkomath
