### ISSUE TITLE
what is difference between freshdesk-api and node-freshdesk-api

### ISSUE THREAD

**Issue by tvrashid** [arjunkomath/node-freshdesk-api#67]
#### what is the difference?
An application which is in production for the past three year built using [node-freshdesk-api](https://www.npmjs.com/package/node-freshdesk-api),now we are facing some issue on freshdesk side so to fix that particular issue we need x-request-id (set by freshdesk server) .Is there any hack to console that x-request-id in that production app itself or we need to migrate to [freshdesk-api](https://www.npmjs.com/package/freshdesk-api) by doing so what are the changes we have to make please explain.

#### Can you add feature?

If migration is the only way to fix that issue,Can you expose that x-request-id response header as a feature.

**Comment by arjunkomath** [comment]
`node-freshdesk-api` is an old version of the package which is no longer maintained. I believe last year we decided to merge our v2 library with another v1 library (https://github.com/kumarharsh/node-freshdesk) together into a single repo and publish it as `freshdesk-api`.

Technically, both `node-freshdesk-api` and `freshdesk-api` are wrappers for V2 API and you should be able to use our latest `freshdesk-api` with your app.

**Comment by arjunkomath** [comment]
Regarding `x-request-id`, is it available on Freshdesk v2 API?

**Comment by tvrashid** [comment]
@arjunkomath 
Yes is it available in response header.
![Screenshot (4)](https://user-images.githubusercontent.com/44792518/68194400-f501cc80-ffda-11e9-8f46-5f1de0bc66d3.png)

**Comment by tvrashid** [comment]
Is it ok if I just include that ```freshdek-api``` and leave the rest of code as it is 
or I have to change any method if there is breaking changes for it.

**Comment by arjunkomath** [comment]
As far I remember there are no breaking changes, but its always good to test thoroughly.

**Comment by arjunkomath** [comment]
I've added `requestId` and you can expect it in `v2.9.0` release.

**Comment by arjunkomath** [comment]
Released https://github.com/arjunkomath/node-freshdesk-api/releases/tag/v2.9.0
🥂

**Comment by tvrashid** [comment]
Thank you so much @arjunkomath
