### ISSUE TITLE
Add requestId even if the requset fail.

### ISSUE THREAD

**Issue by tvrashid** [arjunkomath/node-freshdesk-api#69]
* [  ] freshdesk-api V2

## Current behavior

The extra arg only returns requestId iff the request is successful.

## Expected behavior

Can you please add that requsetId even if the request fails since we need requestId only to trace the error.

###### The below screenshot is response header with requestId set by freshdesk in failed request.
![Screenshot (7)](https://user-images.githubusercontent.com/44792518/68279672-ef1ef080-0099-11ea-8fe8-5fc9e010d28a.png)
#68 #67

**Comment by arjunkomath** [comment]
Fixed in `v2.9.1`, you will get `requestId` inside the error object.

**Comment by tvrashid** [comment]
Thank you so much @arjunkomath
